[features]
seeds = false
skip-lint = false
[programs.localnet]
multiplayer = "DgVtNY9ZPv68mmj69Hxo4pFTwo4RxfdCziy8irHj8dzp"
[programs.devnet]
multiplayer = "DgVtNY9ZPv68mmj69Hxo4pFTwo4RxfdCziy8irHj8dzp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/oliverlinux/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
